### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by kf6kjg**
Brings the library and tools up to spec on using NuGet for package management and product delivery.

Also sets it for .NET 4.6, though that can be reverted if called for.

### CODE REVIEW

**Comment by kf6kjg** [comment]
This might be a fix for #1 as well, but it looked like that had already been more-or-less done.

**Comment by kf6kjg** [comment]
Was already reverted to 4.5 due to Mono needs.

**Comment by kf6kjg** [comment]
Now updated to 4.6.1 since I learnt that Mono can handle it (duh).  Yes, Halcyon needs to come along for the ride too.  But Halcyon doesn't have to pull the latest from here until Halcyon is good and ready for NuGet packages.  Meanwhile I've got several tools using this that have already updated - and LibreMetaverse is already updated.  It's time.

**Comment by appurist** [comment]
The whipclone and whipstress App.config files still specify 4.5, but if you think those should be updated too, just add another PR.  I think your last comment about Halcyon optionally picking this stuff up while allowing other projects to move forward is critical here. Halcyon will likely lag on this until we continue the nuget work but in the meantime let's use the other projects as guinnea pigs here ;)

**Pull request merged**
